<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>elf</string>
	</array>
	<key>name</key>
	<string>Twelf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#blockComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lineComment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-z0-9_\-][A-Za-z0-9_\-/\\\*\'^+]*)\s*:</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Atomic Declaration</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.function.twelf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineComment</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Just Keywords</string>
					<key>match</key>
					<string>type</string>
					<key>name</key>
					<string>constant.language.twelf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arrows</string>
					<key>match</key>
					<string>(\-&gt;|&lt;\-)</string>
					<key>name</key>
					<string>keyword.operator.twelf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Grouping Operators</string>
					<key>match</key>
					<string>\{|\}|\(|\)|:</string>
					<key>name</key>
					<string>keyword.character.escape</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Meta Variables</string>
					<key>match</key>
					<string>[A-Z_][A-Za-z0-9_\-/\\\*\'^+]*</string>
					<key>name</key>
					<string>variable.language.twelf</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Standard Variables</string>
					<key>match</key>
					<string>[a-z0-9\-][A-Za-z0-9_\-/\\\*\'^+]*</string>
					<key>name</key>
					<string>variable.parameter.twelf</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%(name|worlds|block|mode|total|freeze|terminates|covers|unique|abbrev)</string>
			<key>comment</key>
			<string>Other Directives</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>support.typedef.twelf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lineComment</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>\%\{</string>
			<key>comment</key>
			<string>Block Comment</string>
			<key>end</key>
			<string>\}\%</string>
			<key>name</key>
			<string>comment.block.twelf</string>
		</dict>
		<key>lineComment</key>
		<dict>
			<key>begin</key>
			<string>\%\%</string>
			<key>comment</key>
			<string>Line Comment</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.twelf</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.twelf</string>
	<key>uuid</key>
	<string>6b5536a4-8b6d-4f22-9470-66f5f4d8a052</string>
</dict>
</plist>
